[package]
name = "javascriptcore-rs-sys"
version = "0.4.0"
authors = [ "The Gtk-rs Project Developers" ]
description = "Sys functions for the Rust bindings of the javacriptcore library"
repository = "https://github.com/tauri-apps/javascriptcore-rs"
license = "MIT"
keywords = [ "javascript", "gtk-rs", "gnome" ]
build = "build.rs"
edition = "2018"

[package.metadata.system-deps.javascriptcoregtk_4_1]
name = "javascriptcoregtk-4.1"
version = "2.24"

[package.metadata.docs.rs]
features = [ "dox" ]

[lib]
name = "javascriptcore_rs_sys"

[dependencies]
libc = "0.2"
glib-sys = "^0.15"
gobject-sys = "^0.15"

[build-dependencies]
system-deps = "5"

[dev-dependencies]
shell-words = "1.0.0"
tempfile = "3"

[features]
v2_28 = [ ]
dox = [ ]
